### ISSUE TITLE
Distance Matrix arguments did not match any overloaded cal

### ISSUE THREAD

**Issue by Fragoso09** [nilsnolde/orstools-qgis-plugin#100]
#### Here's what I did
Distance Matrix was running ok and after the update it's showing me this error: 

              **TypeError: arguments did not match any overloaded call:
              post(self, QNetworkRequest, QIODevice): argument 2 has unexpected type 'dict'
              post(self, QNetworkRequest, Union[QByteArray, bytes, bytearray]): argument 2 has unexpected type 'dict'
              post(self, QNetworkRequest, QHttpMultiPart): argument 2 has unexpected type 'dict'**

Probably related with networkaccessmanager.py

**Comment by nilsnolde** [comment]
just uploaded the fix to the repository. should be available within the day.
