### ISSUE TITLE
Rate limit response headers should be optional

### ISSUE THREAD

**Issue by nilsnolde** [nilsnolde/orstools-qgis-plugin#102]
local ORS installation don't have those headers obviously.. 

Ref. #99

**Comment by SlowMo24** [comment]
Perfect, thank you! Your response was super quick and on point!
Just for the reference:
I changed Line 201 in `core/client.py` to 
```
        if False:
```

**Comment by nilsnolde** [comment]
Nice, happy to hear that:)

**Comment by nilsnolde** [comment]
When you added a new provider to `config.yml`, I guess you also copied the `ENV_VAR` section, right? If you omit that it should work. 

Anyways, it's related to #103. When that works again, this issue will solve itself.

**Comment by nilsnolde** [comment]
uploaded in plugin repo
