### ISSUE TITLE
provide processing algorithms

### ISSUE THREAD

**Issue by noerw** [nilsnolde/orstools-qgis-plugin#41]
Is there a way to use this plugin (fetch isochrones) from other python code?

If not, the cleanest way would be to encapsulate the API-fetch and data transformation in an [processing provider](https://docs.qgis.org/testing/en/docs/pyqgis_developer_cookbook/processing.html).
I would do this myself, but I do not understand the program flow yet:
The request logic seems to be in [`accRequest()`](https://github.com/nilsnolde/ORStools/blob/master/osm_tools_access.py#L128), which is called from `iterAnalysis()`. Can `accRequest()` be called with any list of `QgsGeometry`, or are there additional preconditions?

**Comment by nilsnolde** [comment]
I reserved two days this week to re-write a lot of the plugin, hopefully finished by end of next week.

It's been a bit unstable from the last release on anyways, plus I need to upgrade to QGIS3. After the upgrade, I'll refactor quite a bit. I wrote this [PyPI version](https://github.com/GIScience/openrouteservice-py) for ORS. That's when I realized how poorly written the plugin is.. But the Py package could get you off the ground for now.

So, don't spend any of your resources on this for now (even though highly appreciated!). I'll let you know when I'm happy again with the plugin:) And I will heed your suggestion, I think that'd be a great addition!

**Comment by noerw** [comment]
Alright, thanks for the effort! Will look into the PyPI version.

**Comment by nilsnolde** [comment]
@noerw Wanna take this on? I just completed refactoring for v3

**Comment by noerw** [comment]
Yeah, would like to help you out! I'm not sure though when I will get it done

**Comment by nilsnolde** [comment]
Right. I'd like to backport this again to v2.x anyways. Hopefully this week. v.2.18 be LTS for quite a while I imagine. Lots of companies won't do the switch to v3 before. 

I'm just thinking of adding our matrix API before, to output large amounts of routings to a table (since it doesn't provide geometries). 

What will adding the tool to processing module mean anyways (I get the benefits that'd add, I mean in terms of code change)? The GUI is then internally managed in QGIS right? So, it'd be an entire rewrite of GUI related things?

**Comment by noerw** [comment]
Exactly. You don't write any GUI code at all, you only define a subclass of `GeoAlgorithm`, specify parameters and outputs, and a `processAlgorithm()` function implementing the logic.
This GeoAlgorithm is then registered with an `AlgorithmProvider`, which can group several `GeoAlgorithms`.

[QuickOSM](https://github.com/3liz/QuickOSM/tree/master/quick_osm_processing) is a plugin that has both a custom UI and a processing provider. They separated the core logic quite nicely to be used in both the UI and Processing. I would do it in a similar way

backporting sounds great!

**Comment by nilsnolde** [comment]
Yeah, sounds pretty cool actually.. You’d miss out on advanced gui features like the map buttons, but you’d be able to use it in modelling.. that’s surely a good tradeoff.

Let me include the matrix api on the weekend (should be a quick one), then proccesing makes even more sense.

**Comment by nilsnolde** [comment]
Sooo, it's all done for a while, I hope: 
- added the matrix API to v3.1
- backported to QGIS v2.1

pcav already approved, so you can have a look.

**Note**, I did most of the dev on Linux, only the backport on Win. Now, I realized, that the GUI is not really consistent across platforms. It's behaving weird on Linux, maybe some QtBackend stuff.. Anyways, didn't care really, just wanna be done;)

**Comment by jbdesbas** [comment]
> 
> 
> Yeah, sounds pretty cool actually.. You’d miss out on advanced gui features like the map buttons, but you’d be able to use it in modelling.. that’s surely a good tradeoff.
> 
> Let me include the matrix api on the weekend (should be a quick one), then proccesing makes even more sense.

Today, it is possible to add a [parameterPoint](https://qgis.org/pyqgis/3.2/core/Processing/QgsProcessingParameterPoint.html?highlight=qgsprocessingparameterpoint) to get coordinates by clic the map (see the processing alog `qgis:serviceareafrompoint` as exemple).

**Comment by nilsnolde** [comment]
Finally in there. It's active in the current development branch. 

@noerw I reaaally tried to get the difference operation to the isochrone algo. It's not easy and way different the v3.x API compared to your original implementation in v2.x. One has to postprocess the polygon output, but I couldn't get the postprocessing method to see the dissolved layer held in memory. Smth to do with processing contexts.. As far as I could tell I did it all correctly, still didn't work. Anyways, I guess it could work with Tmp files, but I don't like writing to disk. If you ever wanna have a shot at this:

Postprocessing method (sorry, I unfortunately deleted my attempt):
https://github.com/nilsnolde/OSMtools/blob/ffbe6bed72d41acfdcc84e62fe6dc41ef42794f9/ORStools/proc/isochrones_proc.py#L219

First shot to get at least the dissolve layer reported back to the postprocessing method:
https://github.com/nilsnolde/OSMtools/blob/ffbe6bed72d41acfdcc84e62fe6dc41ef42794f9/ORStools/core/isochrones_core.py#L114

**Comment by nilsnolde** [comment]
fixed in newest master and available in plugin repo
