### ISSUE TITLE
OSMTools via Proxy?!

### ISSUE THREAD

**Issue by ghost** [nilsnolde/orstools-qgis-plugin#58]
It looks like OSMTools don't work in a proxy server environment.
Would it be possible for the plugin to use the proxy settings configured in the QGIS Network Settings?
Or is there already a workaround?

Maybe one of the following is useful?
https://qgis.org/api/classQgsNetworkAccessManager.html
https://geogear.wordpress.com/2014/04/12/setting-proxy-parameter-in-qgis-plugins-how-to/

Error Message:
"...requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.openrouteservice.org', port=443): Max retries exceeded with url: /geocoding?location=9.16237%2C48.77638&api_key=[XXX] (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x00000000056724E0>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed',))..."

**Comment by nilsnolde** [comment]
Perfect, thanks for the tip!
