### ISSUE TITLE
'from layer' does not work when layers are grouped

### ISSUE THREAD

**Issue by fluegelrad** [nilsnolde/orstools-qgis-plugin#74]
Moin Nils,

I've tried calculating a matrix from single point layers w/ OSMtools in QGIS 3.2.3.
OSMtools would'nt let me select my input layers in the dropdown menu – similarly to [D-Leenders' problem over here](https://github.com/nilsnolde/OSMtools/issues/47#issuecomment-425940281).

After half a day of desperate endeavour (collateral damage: a coffee mug and plenty of cookies) i figured out the problem: **The layers are not selectable when they're grouped**. Haven't checked on different QGIS configurations but I could reproduce this bug in three different projects.

#### When input layers are grouped it looks like this:
![grafik](https://user-images.githubusercontent.com/44899934/48266807-d3eeb600-e430-11e8-8009-7b50d3380824.png)
![grafik](https://user-images.githubusercontent.com/44899934/48266930-292ac780-e431-11e8-876b-8851e92e7e69.png)

#### When input layers are not grouped it looks like that:
![grafik](https://user-images.githubusercontent.com/44899934/48267153-dbfb2580-e431-11e8-89da-83f041a6d10c.png)
![grafik](https://user-images.githubusercontent.com/44899934/48267136-cf76cd00-e431-11e8-980b-47949e59a5fb.png)

Hope that helps. Thx for your great plugin!
Regards from Hamburg
/Christoph

OS: WIN10 1803 / build 17134.345
QGIS 3.2.3

**Comment by nilsnolde** [comment]
aaah thx for clearing up the mystery!! (somehow feels like a deja-vue.. did I answer this in my dreams..)

Once more: in the process of refactoring! ETA ~ 1-2 weeks.

**Comment by nilsnolde** [comment]
It's coming along on the refactoring:) There's a stable version in `development` branch, where this issue is fixed. Happy now with GUI and functionality, only needs a little work on exposing Processing Algorithms.

Keeping open as long as `master` is not updated.

**Comment by alpter** [comment]
I tryed using some layer but they  do not show on "from layer" tab that remains un-clickable either gruped or normally listed ....  The only function allowed is "from map" function that works great :-)




OS: WIN10 PRo
on 
Versione di QGIS | 3.4.0-Madeira | Revisione codice QGIS | 4a4b62ed19
-- | -- | -- | --
Compilato con Qt | 5.11.2 | Esecuzione con Qt | 5.11.2
Compilato con GDAL/OGR | 2.3.2 | Esecuzione con GDAL/OGR | 2.3.2
Compilato con GEOS | 3.7.0-CAPI-1.11.0 | Esecuzione con GEOS | 3.7.0-CAPI-1.11.0 673b9939
Versione client PostgreSQL | 9.2.4 | Versione SpatiaLite | 4.3.0
Versione QWT | 6.1.3 | Versione QScintilla2 | 2.10.8
Compiled against PROJ | 520 | Running against PROJ | 5.2.0

**Comment by nilsnolde** [comment]
And it's Point layers? And it's single geometry Point layers and not MultiPoint layers? One of those conditions has to be false in your case.

Also, try to install the development branch. That version is a lot better (even if not fully stable yet, more stable than the previous one..).

**Comment by alpter** [comment]
ThanX . Just upgraded Qgis to last version | 3.4.2-Madeira |  QGIS | 22034aa070 and now it works... with Point layers !
Would be useful however if you could use simple "multilinestring" shp for routing....  would it be difficult/possible to codify ?

**Comment by alpter** [comment]
> Would be useful however if you could use simple "multilinestring" shp for routing.... would it be difficult/possible to codify ?

This refer to this ... sorry :  
https://github.com/nilsnolde/OSMtools/issues/80

**Comment by nilsnolde** [comment]
fixed in newest master and available in plugin repo
