### ISSUE TITLE
the "from layer" function does not work

### ISSUE THREAD

**Issue by vigerpaulalexandrests** [nilsnolde/orstools-qgis-plugin#85]
It is impossible to select a point layer when checking the "Use Layer" option. For example, with the isochrone, I can only generate an isochrones with the "Map now!" function but not with the "Use Layer". I tried "Refresh List" a couple of times but I still can't select a point layer.

![issue](https://user-images.githubusercontent.com/46690650/51139086-e4e0ec80-1810-11e9-92e1-dea87d33cc2f.PNG)

**Comment by nilsnolde** [comment]
Hi, sorry for the late response!

Try the `development` branch. Instructions are in the README. New UI and lots of new functionality. And a looot more stable. However, the issue pertains if you try to use `MultiPoint` layers. It has to be single point geometries. Convert to single part if necessary.

A new release will come in a few days/weeks.

**Comment by nilsnolde** [comment]
no response and duplicate
