### ISSUE TITLE
Please add a more relevant home page

### ISSUE THREAD

**Issue by pcav** [nilsnolde/orstools-qgis-plugin#89]
It should not be an advertisment of your company, but an informative page about the plugin functionality.
Thanks.

**Comment by pcav** [comment]
You acn fix the link directly on the website, and change metadata in the meantime, so next version will be OK

**Comment by nilsnolde** [comment]
Oops, sorry, I found the delete button in the meantime. 

Anyways, I fixed it and will upload again. Sorry for the hassle!
