### ISSUE TITLE
Distance Matrix

### ISSUE THREAD

**Issue by gillyjuwa** [nilsnolde/orstools-qgis-plugin#96]
Hello Open Route Service team,

1. I was using the distance matrix calculator and it has disappeared from the API playground. Has it gone forever?

2. I have tried using the  /v2/matrix/{profile} Post Matrix Service instead but it keeps returning the following error:

 
- 
{ 
-
"error"
: 
{
"message"
: 
"Could not write JSON: (was java.lang.ArrayIndexOutOfBoundsException); nested exception is com.fasterxml.jackson.databind.JsonMappingException: (was java.lang.ArrayIndexOutOfBoundsException) (through reference chain: heigit.ors.api.responses.matrix.JSONMatrixResponseObjects.JSONMatrixResponse[\"matrix\"])" 
}
,
-
"info"
: 
{
-
"engine"
: 
{
 
"version"
: 
"5.0"
,
"build_date"
: 
"2019-02-28T09:50:25Z"
}
,
"timestamp"
: 
1553498615887
}
}
 
I was using the original distance matrix over large distances . Is this the issue here?

Please would you help me get up and running again.

Kind regards

Gillian

**Comment by nilsnolde** [comment]
Nothing to do with the QGIS client...
