### ISSUE TITLE
Get rid of the quota option for ORS, useless

### ISSUE THREAD

**Issue by nilsnolde** [nilsnolde/orstools-qgis-plugin#97]
Can produce negative sleeps, which crashes the app of course.. 

Ref. https://ask.openrouteservice.org/t/quota-not-being-reset/406/3?u=nils

**Comment by nilsnolde** [comment]
Workaround is to specify much higher rate limits in the configuration settings than actually allowed, as suggested by **cimar**:
https://ask.openrouteservice.org/t/quota-not-being-reset/406/5

**Comment by Saijin-Naib** [comment]
Just hit this with the ORS QGIS plugin. I worked around it by setting my rate/quota very low.
